### ISSUE TITLE
In Edge browser, moveToElement is not working , Same code id working fine in Chrome & firefox

### ISSUE THREAD

**Issue by prashant1514** [prashant1514/SelniumAutomation#2]
Hi All,

There are 2 links in our Application, to click on them u have used Actions class, and using moveToElement clicking on them. 

Code is working fine in Chrome & Firefox. But, its not working in edge browser 

Edge version: 18

@When("^User clicks on \"([^\"]*)\"$")
	public void user_clicks_on(final String transactions) throws Throwable {
		try {
			usablemethods.Waittime();
			final String Transactions1 = LocalTestDataManager.getTestDataHashMap().get(transactions).trim();
			LocalDriverManager.getLogger().log(LogStatus.PASS, "Business Transaction link text is " + Transactions1);
			Assert.assertTrue(true, "Business Transaction link text is " + Transactions1);
			if (Transactions1.equals("")) {
				LOG.info("User has not clicked on Business Transaction link as business Transaction link is blank");
				LocalDriverManager.getLogger().log(LogStatus.FAIL,
						"User has not clicked on Business Transaction link as business Transaction link is blank"
								+ LocalDriverManager.getLogger().addScreenCapture(
										usablemethods.takescreenshot(LocalTestDataManager.getScenarioname())));
				Assert.assertTrue(false,
						"User has not clicked on Business Transaction link as business Transaction link is blank");
			} else {
				final WebElement element = LocalDriverManager.getDriver().findElement(By.linkText(Transactions1));
				usablemethods.Waittime();
				final Actions action = new Actions(LocalDriverManager.getDriver());
				action.moveToElement(element).build().perform();
				usablemethods.Waittime();
				LOG.info("User has clicked on Business Transaction link::PASS");
				LocalDriverManager.getLogger().log(LogStatus.PASS, "User has clicked on Business Transaction link");
				Assert.assertTrue(true, "User has clicked on Business Transaction link");
			}
		} catch (final Exception exception) {
			LOG.error("Failed to check if user has clicked on the business transaction link::FAIL::{}",
					exception.getMessage());
			LocalDriverManager.getLogger().log(LogStatus.FAIL,
					"Failed to check if user has clicked on the business transaction link"
							+ LocalDriverManager.getLogger().addScreenCapture(
									usablemethods.takescreenshot(LocalTestDataManager.getScenarioname())));
			Assert.assertTrue(false, "Failed to check if user has clicked on the business transaction link");
		}
	}

	@When("^User and select \"([^\"]*)\"$")
	public void user_and_select(final String transactionOption) throws Throwable {
		try {
			final String transaction_Option = LocalTestDataManager.getTestDataHashMap().get(transactionOption);
			if (transaction_Option.equals("")) {
				LOG.info("User has clicked on Business Transaction Option link as it is not present ");
				LocalDriverManager.getLogger().log(LogStatus.FAIL,
						"User has clicked on Business Transaction Option link as it is not present "
								+ LocalDriverManager.getLogger().addScreenCapture(
										usablemethods.takescreenshot(LocalTestDataManager.getScenarioname())));
				Assert.assertTrue(false,
						"User has not clicked on Business Transaction Option link as it is not present ");
			} else {
				LocalDriverManager.getDriver().findElement(By.linkText(transaction_Option)).click();
				LocalDriverManager.getLogger().log(LogStatus.PASS,
						"User has clicked on " + transaction_Option + " link");
				Assert.assertTrue(true, "User has clicked on " + transaction_Option + " link");
				usablemethods.Waittime();
			}
		} catch (final Exception exception) {
			LOG.error("Failed to check if user clicked on Business Transaction Option link::FAIL::{}",
					exception.getMessage());
			LocalDriverManager.getLogger().log(LogStatus.FAIL,
					"Failed to check if user clicked on Business Transaction Option" + LocalDriverManager.getLogger()
							.addScreenCapture(usablemethods.takescreenshot(LocalTestDataManager.getScenarioname())));
			Assert.assertTrue(false, "Failed to check if user clicked on Business Transaction Option");
		}
	}

Console:
 INFO [TestNG] (chevron_HomePage.java47) - User has clicked on Business Transaction link::PASS
ERROR [TestNG] (chevron_HomePage.java82) - Failed to check if user clicked on Business Transaction Option link::FAIL::The specified element was not found in the current frame or window.
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:14.666Z'
System info: host: 'DEPOVM22', ip: '146.36.126.51', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.remote.RemoteWebDriver

java.lang.AssertionError: Failed to check if user clicked on Business Transaction Option expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.chevron.steps.chevron_HomePage.user_and_select(chevron_HomePage.java:87)
	at com.chevron.steps.chevron_HomePage.user_clicks_on_and_select(chevron_HomePage.java:94)
	at ?.When User clicks on "transactions_1" and select "transactionOption_1"(src/test/resources/features/AviationAirportDetails.feature:91)

Could some one please help me in resolving this issue. I want the code to work fine in Chrome, Firefox & Edge !

**Comment by RapidRavi** [comment]
Is it for Selenium 3 or 4?
